### ISSUE TITLE
Realizar Diagrama de clases

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#137]
***Crear el Diagrama de Clases***  (modelo de objetos). Pueden usar como herramienta también https://app.diagrams.net/

-  Identificar los nombres de las clases
- Distinguir las relaciones
- Crear la estructura

*Ejemplo diagrama de clases*

![Image](https://user-images.githubusercontent.com/99567012/197031369-25cd74ac-3612-41c4-9baf-49958e9f3f09.png)

*Ejemplo especifico UML  tipo MVC*

![Image](https://user-images.githubusercontent.com/99567012/197031715-2925e959-0b8e-45f6-a571-193d5f92d096.png)

**Comment by Lucas-Balduzzi** [comment]
Consulta... esto es solo a modo orientativo para empezar a armarlo?

**Comment by Noobuyer** [comment]
@Lucas-Balduzzi yo creeria que si

**Comment by Noobuyer** [comment]
Se sube desarrollos de rama personal.

**Comment by Noobuyer** [comment]
Cargado en branch develop.

**Comment by mariquenaallosa** [comment]
https://github.com/MarcofCorrea/ProyectoFullstack/wiki/Diagrama-de-clases
