### ISSUE TITLE
#TK80 Cambiar estilo del botón ir de cllima y calendarios

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#140]
En el archivo index.html se encuentra una sección llamada clima y calendarios , la idea es que el botón de ir tenga la misma estética que los botones de ver más.
En este momento los botones del IR>> se encuentran de la siguiente manera

![Image](https://user-images.githubusercontent.com/99567012/197027058-93647e4c-b507-422e-b581-920c90f238ab.png)

y sería óptimo que tengan el mismo estilo que los botones de ingreso o ver más:

![Image](https://user-images.githubusercontent.com/99567012/197027219-f9306aac-31ee-43cc-9379-bf6c2360a721.png)  ![Image](https://user-images.githubusercontent.com/99567012/197027290-d3cb0c85-eb39-4a1d-9e74-7e87b844c2df.png)

Trabajar el estilo sobre el archivo que se encuentra en css/styles.css en la sección marcada con comentarios 

- Dar una clase propia al botón, la cual se utilizará en la hoja de estilos
- Se puede copiar los valores de btn-more que se encuentran en la misma hoja de estilos.(styles.css)
- Cambiar valores hasta conseguir que sea utilizable y visible.

**Comment by Lucas-Balduzzi** [comment]
Necesita mejoras, pero cerca del objetivo
