### ISSUE TITLE
Realizar Sitio Institucional en WordPress

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#145]
Adjunto el documento con las consignas y alcance de la tarea

[Instancia evaluativa SGC.pdf](https://github.com/MarcofCorrea/ProyectoFullstack/files/9884821/Instancia.evaluativa.SGC.pdf)

**Comment by Noobuyer** [comment]
Subo material de rama personal.

**Comment by Noobuyer** [comment]
Avance con dificultades debido a xampp con mysql cargado en branch developer, se instala bitnami y se procede a la creacion de un sitio de 0.

**Comment by Noobuyer** [comment]
Realizado carga de cv, seccion integrantes.

**Comment by Noobuyer** [comment]
Subida 3 experiencias en sitio grupal institucional.

**Comment by mariquenaallosa** [comment]
CV actualizado
