### ISSUE TITLE
#TK16 incorporar información de clima

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#20]
Creación archivo .html de la sección clima con su información correspondiente y hoja de estilo propia . el archivo HTML deberá incluir:

- Header 
- nav
- seccion clima
- footer

**Comment by Lucas-Balduzzi** [comment]
Header, nav, footer agregado.
Nueva presentación de sección  del clima, aún en proceso de división de la información.
