### ISSUE TITLE
#TK01 Desarrollo de identidad

### ISSUE THREAD

**Issue by MarcofCorrea** [MarcofCorrea/ProyectoFullstack#3]

**Comment by 1pame** [comment]
*Lista idea nombre del portal de pesca* 
Verificada en nic.ar
Sometida a votación. 

-------------  .com.ar 

• lamojarraviva
• notipesca
• acciondepesca 
• elanzuelo
• elseñuelo
• pescapositiva
• lapesca
• pescayturismo
• NotiPez

**Comment by 1pame** [comment]
Nombre ganador del portal de pesca: elanzuelo
