### ISSUE TITLE
#TK05 Definir maquetas visuales/bocetos Shop

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#42]

**Comment by Noobuyer** [comment]
#TK05 - Definir maquetas visuales/Bocetos Shop 

-Documento a entregar
-Esquema
-Información
-Funcionalidades

**Comment by Noobuyer** [comment]
![image](https://user-images.githubusercontent.com/85040272/193385246-aebad1e0-e5ce-44fe-a22d-5c8be432b203.png)
![image](https://user-images.githubusercontent.com/85040272/193385545-04919edc-dcf9-42cb-b3ea-7df1ee86e2d8.png)

**Comment by mariquenaallosa** [comment]
- Funcionalidades
- Esquemas
- Documentación

**Comment by mariquenaallosa** [comment]
- Vista de la sección
- Vista de todos los productos
- Vista de producto
- Vista de carrito
- Vista de pago - informacion de envio
- Vista de envio 
- Vista de pago

**Comment by Noobuyer** [comment]
[Documento_Maquetacion.zip](https://github.com/MarcofCorrea/ProyectoFullstack/files/9689588/Documento_Maquetacion.zip)

**Comment by mariquenaallosa** [comment]
[#TK05 Shop - Funcionalidades y esquemas.pdf](https://github.com/MarcofCorrea/ProyectoFullstack/files/9691124/TK05.Shop.-.Funcionalidades.y.esquemas.pdf)

**Comment by mariquenaallosa** [comment]
0ea869663fb459b62dd3dde42bfce86a55e86ef7 resuelto
