### ISSUE TITLE
#TK07 Definir maquetas visuales/bocetos Inicio de sesión / registro

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#50]

**Comment by Martin-91** [comment]
[TK 07 Definir maquetas visuales Inicio de sesion.pdf](https://github.com/MarcofCorrea/ProyectoFullstack/files/9693837/TK.07.Definir.maquetas.visuales.Inicio.de.sesion.pdf)
