### ISSUE TITLE
#TK10 Definir maquetas visuales/bocetos Calendario de pesca por ciudad

### ISSUE THREAD

**Issue by mariquenaallosa** [MarcofCorrea/ProyectoFullstack#53]

**Comment by 1pame** [comment]
[Pesca ARGENTINA, Calendario anual.pdf](https://github.com/MarcofCorrea/ProyectoFullstack/files/9698250/Pesca.ARGENTINA.Calendario.anual.pdf)

**Comment by 1pame** [comment]
[Esquema Pesca ARGENTINA, Calendario anual.pdf](https://github.com/MarcofCorrea/ProyectoFullstack/files/9701101/Esquema.Pesca.ARGENTINA.Calendario.anual.pdf)
