### ISSUE TITLE
Registro en la Wiki

### ISSUE THREAD

**Issue by Lucas-Balduzzi** [MarcofCorrea/ProyectoFullstack#7]
Breve resumen del Inicio del Proyecto.
Punto de partida.
Y breve resumen de 1º Meeting.

**Comment by mariquenaallosa** [comment]
Meeting registrada

**Comment by Lucas-Balduzzi** [comment]
Perfect! 😄

**Comment by mariquenaallosa** [comment]
Actualización de Wiki , adjuntando la distribución de tareas
