### ISSUE TITLE
Carga de documentación

### ISSUE THREAD

**Issue by MarcofCorrea** [MarcofCorrea/ProyectoFullstack#70]

**Comment by MarcofCorrea** [comment]
Subir formulario 830.PDF, manual estilo logo.PDF, mapa de sitio.pdf a la rama main (en carpetas diferente) por medio de Gitbush (Clonar repositorio a la compu)

**Comment by JoseRighetti** [comment]
![Image](https://user-images.githubusercontent.com/106637121/193723881-4ac3db22-7334-4a55-bacf-2408a2c42c14.png)
