### ISSUE TITLE
#US21 como visitante quiero tener una sección de contacto para comunicarme con los responsables de la pagina

### ISSUE THREAD

**Issue by MarcofCorrea** [MarcofCorrea/ProyectoFullstack#98]
- [ ] https://github.com/MarcofCorrea/ProyectoFullstack/issues/114
- [x] https://github.com/MarcofCorrea/ProyectoFullstack/issues/115
- [ ] https://github.com/MarcofCorrea/ProyectoFullstack/issues/116

**Comment by Noobuyer** [comment]
Completado, se sube a rama develop.

**Comment by Noobuyer** [comment]
Modificado los campos, se sube a rama develop.
